### ISSUE TITLE
Ip is not register

### ISSUE THREAD

**Issue by nurzaly** [hymns/infoblast-openapi#1]
Macamana nak settlekan Ip is not register. 

Thanks

**Comment by hymns** [comment]
Email kat helpdesk[at]tab.com.my  untuk enable api untuk ur account.

**Comment by hymns** [comment]
Email kat helpdesk[at]tab.com.my  untuk enable api untuk ur account.

**Comment by amin007** [comment]
sudah lupa tentang koding ini
